### ISSUE TITLE
Action not found

### ISSUE THREAD

**Issue by insideth** [ColdTrick/quicklinks#4]
When you click the link listed from the quicklinks site menu. Tested in Elgg 2.1

**Comment by jdalsem** [comment]
What link are you talking about? Quicklinks does not register a site menu item....

**Comment by jdalsem** [comment]
@insideth could you answer my question above?

**Comment by insideth** [comment]
Sorry @jdalsem, y tested the plugin with theme_haarlem_intranet enabled, and with this theme a quicklinks site menu is displayed, so the issue come from this theme.

**Comment by jdalsem** [comment]
Not experiencing this on the website where we use the theme
